### ISSUE TITLE
validation error during training

### ISSUE THREAD

**Issue by lostnighter** [sibeiyang/sgmn#4]
Hi sibei,
    Thanks for your great work! When I run   bash experiments/script/train.sh $GPUs (max_epochs is set 10), an error as below occured after epoch=4 training and during epoch=4 validation. It is strange that the former validations (epoch=0,1,2,3) do not have this error, while this validation (epoch=4) has this error. However,  validation of epoch=0,1,2,3 and epoch=4 use the same data. Have you encountered this error?

Epoch: [4][10800/11269] Loss 0.9439 (1.1169)    Prec 0.5863
Epoch: [4][10900/11269] Loss 1.1050 (1.1168)    Prec 0.5903
Epoch: [4][11000/11269] Loss 1.1638 (1.1170)    Prec 0.5780
Epoch: [4][11100/11269] Loss 1.1370 (1.1168)    Prec 0.5905
Epoch: [4][11200/11269] Loss 1.0406 (1.1167)    Prec 0.5948
Traceback (most recent call last):
  File "./tools/train.py", line 257, in <module>

  File "./tools/train.py", line 110, in main
    for epoch in range(epoch_cur, opt['max_epochs']):
  File "./tools/train.py", line 202, in validate
    sents, sents_gt, gt_boxes, img_ids, sent_ids,
  File "/backup1/home/jlgao/anaconda2/envs/torch4/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/backup1/home/jlgao/anaconda2/envs/torch4/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/backup1/home/jlgao/anaconda2/envs/torch4/lib/python2.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/backup1/home/jlgao/anaconda2/envs/torch4/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/backup1/home/jlgao/anaconda2/envs/torch4/lib/python2.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/backup1/home/jlgao/jlgao/controllable/sgmn/tools/../lib/datasets/refdataset_sg_online.py", line 44, in __getitem__
    roi_feature = self.refdb.h5_files[file]['features'][idx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/backup1/home/jlgao/anaconda2/envs/torch4/lib/python2.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad object header version number)'

Thanks
Junlong

**Comment by sibeiyang** [comment]
Hi @lostnighter ,

I did not encounter this error. Did you set num_worker > 1 ? 

Best,
Sibei

**Comment by lostnighter** [comment]
> Hi @lostnighter ,
> 
> I did not encounter this error. Did you set num_worker > 1 ?
> 
> Best,
> Sibei

yes. when set num_workers > 1, this error will occur, because h5 files ( e.g. gt_objects_*.h5 and lrel_gt_objs_*.h5) are opened under default setting and read via multiprocessing. And when I set h5py.File(path, 'r', libver='latest', swmr=True) in Line 32 and 56 in lib.datasets.roidb, the error will disappear.
